name: mne_current
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - mne
  - customtkinter
  - matplotlib
  - tqdm
  - ipykernel
  - pandas
  - ipython
  - mne-icalabel
  - ipdb
  - autoreject
