Zuerich:
  source_analysis: true
  mri: true
  subjects_fs_dir: "/Applications/freesurfer/7.4.1/subjects"
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Austin:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Dublin:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Ghent:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Illinois:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Regensburg:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"

Tuebingen:
  source_analysis: true
  mri: false
  manual_data_scroll: true
  automatic_epoch_rejection: false
  create_report: true
  verbose: "ERROR"
