events:
  pre:
    PO70: 11
    PO75: 12
    PO80: 13
    PO85: 14
    PO90: 15
  bbn:
    PO: 21
    GO: 22
    GP: 23
  3kHz:
    PO: 31
    GO: 32
    GP: 33
  8kHz:
    PO: 41
    GO: 42
    GP: 43
  post:
    PO70: 51
    PO75: 52
    PO80: 53
    PO85: 54
    PO90: 55
default_thresholds:
  Zuerich:
    pre:
    - 850
    - 1500
    - 2000
    - 2300
    bbn:
    - 1150
    - 1700
    - 2250
    3kHz:
    - 1150
    - 1700
    - 2250
    8kHz:
    - 1150
    - 1700
    - 2250
    post:
    - 850
    - 1500
    - 2000
    - 2300
  Regensburg:
    pre:
    - 0.003
    - 0.01
    - 0.017
    - 0.02185
    - 0.0285
    bbn:
    - 0.005
    - 0.015
    - 0.021
    - 0.026
    3kHz:
    - 0.005
    - 0.015
    - 0.021
    - 0.026
    8kHz:
    - 0.005
    - 0.015
    - 0.021
    - 0.026
    post:
    - 0.003
    - 0.01
    - 0.017
    - 0.02185
    - 0.0285
  Tuebingen:
    pre:
    - 0.44
    - 0.74
    - 1
    - 1.25
    bbn:
    - 0.61
    - 0.88
    - 1.18
    3kHz:
    - 0.61
    - 0.88
    - 1.18
    8kHz:
    - 0.61
    - 0.88
    - 1.18
    post:
    - 0.44
    - 0.74
    - 1
    - 1.25
